### PR TITLE
Show vr pattern

### PR DESCRIPTION
**Pull request by WanzhuoShi**
This branch is able to show VR pattern now. However, I think that using new classes ("Chess" and "Board") will cause great trouble to the next job. For example, we have to make a lot of changes to these 2 files -- "experiment.h" and "experiment.cpp". 
Maybe I should rewrite this function by original classes. What do you think?
@young24

### CODE REVIEW

**Comment by young24** [comment]
By looking at your code, I think the function can be achieved with Screen, Area, and Patch Classes. Also, I guess you have to write a new method for Patch and rewrite a shader file.
Since it is not a priority, you can do this when you have time. Please let me know when you need help.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
Sure

**Comment by WanzhuoShi** [comment]
I've just rewritten the function by PatchData, AreaData, and ScreenData. If you have time, maybe we could test it on the real device.
@young24

**Comment by young24** [comment]
Code complete. However, since it is an LTS branch, we do not merge this branch with the master branch.

Pull request close.

**Pull request closed without merging**
